# Generated by Django 4.2.26 on 2025-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'region', 'parameter')},
            },
        ),
    ]
